[package]
name = "spin"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
repository = "https://www.github.com/tock/libtock-rs"
rust-version.workspace = true
description = "libtock-rs spin app with embedded graphics"

[dependencies]
embedded-graphics = "0.8.1"
libm = "0.2.15"

libtock = { path = "../../../", version = "0.1.0" }
embedded_graphics_libtock = { path = "../../../libraries/embedded_graphics_libtock", version = "0.1.0" }

[build-dependencies]
libtock_build_scripts = { path = "../../../build_scripts" }
