[profile.dev]
panic = "abort"
lto = true
debug = true

[profile.release]
panic = "abort"
lto = true
debug = true

[workspace]
exclude = ["tock"]
members = [
    "apis/gpio",
    "apis/buttons",
    "apis/console",
    "apis/leds",
    "apis/low_level_debug",
    "libtock2",
    "panic_handlers/small_panic",
    "platform",
    "runner",
    "runtime",
    "syscalls_tests",
    "tools/print_sizes",
    "ufmt",
    "unittest",
]
