[package]
name = "libtock"
version = "0.2.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
core = { package = "async-support", path = "async-support" }
linked_list_allocator = { version = "0.6.4", default-features = false }
libtock-support-macros = { path = "support-macros" }

[dev-dependencies]
corepack = { version = "0.4.0", default-features = false, features = ["alloc"] }
# We pin the serde version because newer serde versions may not be compatible
# with the nightly toolchain used by libtock-rs.
serde = { version = "=1.0.84", default-features = false, features = ["derive"] }
futures = { version = "0.3.1", default-features = false, features = ["unstable", "cfg-target-has-atomic"] }

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
lto = true

[workspace]
members = [
    "async-support",
    "support-macros",
]
