[package]
name = "libtock"
version = "0.2.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[features]
alloc = ["libtock-core/alloc"]

[dependencies]
core = { package = "async-support", path = "async-support" }
libtock-core = { path = "core" }
libtock_codegen = { path = "codegen" }
futures = { version = "0.3.1", default-features = false, features = ["unstable", "cfg-target-has-atomic"] }

[dev-dependencies]
corepack = { version = "0.4.0", default-features = false, features = ["alloc"] }
# We pin the serde version because newer serde versions may not be compatible
# with the nightly toolchain used by libtock-rs.
serde = { version = "=1.0.84", default-features = false, features = ["derive"] }

[[example]]
name = "alloc_error"
path = "examples-alloc/alloc_error.rs"
required-features = ["alloc"]

[[example]]
name = "ble_scanning"
path = "examples-alloc/ble_scanning.rs"
required-features = ["alloc"]

[[example]]
name = "libtock_test"
path = "examples-alloc/libtock_test.rs"
required-features = ["alloc"]

[[example]]
name = "simple_ble"
path = "examples-alloc/simple_ble.rs"
required-features = ["alloc"]

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
lto = true

[workspace]
members = [
    "async-support",
    "codegen",
    "core"
]
