[toolchain]
# This is libtock-rs' Minimum Supported Rust Version (MSRV).
#
# Update policy: Update this if doing so allows you to use a Rust feature that
# you'd like to use. When you do so, update this to the first Rust version that
# includes that feature. Whenever this value is updated, the rust-version field
# in Cargo.toml must be updated as well.
channel = "1.77"
components = ["clippy", "rustfmt"]
targets = [
    "thumbv6m-none-eabi",
    "thumbv7em-none-eabi",
    "riscv32imac-unknown-none-elf",
    "riscv32imc-unknown-none-elf",
]
