[package]
name = "libtock_spi_controller"
version = "0.1.0"
authors = [
    "Tock Project Developers <tock-dev@googlegroups.com>",
    "Alistair Francis <alistair.francis@wdc.com>",
]
license = "Apache-2.0 OR MIT"
edition = "2021"
repository = "https://www.github.com/tock/libtock-rs"
rust-version.workspace = true
description = "libtock SPI controller driver"

[dependencies]
libtock_platform = { path = "../../../platform" }
